### ISSUE TITLE
Lazy iterables - why not use generators ? 

### ISSUE THREAD

**Issue by deanius** [raganwald/raganwald.github.com#42]
Could you not have used generators in http://raganwald.com/2015/02/17/lazy-iteratables-in-javascript.html ? 

As I tried to explain myself the foreign concepts of iterables, in the new ES6 syntax, I wrote this line-by-line explanation of what 'mapIterableWith` was doing.

```
// mapIterableWith
// Accepts a function to map, and an iterable, and...
// returns an object which...
// under the conventionally defined key, contains a 'generator' function which...
// returns an iterator-looking object whose 'next' method...
// returns an object {done: bool, value: fn(x)} for each value in the passed iterable...
// until the passed iterables' end...
const mapIterableWith = (fn, iterable) =>
  ({
    [Symbol.iterator]: () => {
      const iterator = iterable[Symbol.iterator]();
      
      return {
        next: () => {
          const {done, value} = iterator.next();
    
          return ({done, value: done ? undefined : fn(value)});
        }
      }
    }
  });
```

But I feel like it was really micro-managing what's going on, rather than encapsulating alot of that semantics in a function with a `*` part of its name where the behavior is more implied.

```
// mapIterableWith
// Accepts a function to map, and an iterable and ...
// returns a generator which yields values ...
// of the passed function applied to the values of the iterable
const mapIterableWith = (fn, iterable) =>
  ({
    [Symbol.iterator]: function* () {
      const iterator = iterable[Symbol.iterator]();
      yield fn(iterator.next().value);
    }
  });
```

Am I missing something ?

**Comment by raganwald** [comment]
You are correct!

This was extracted from a chapter in my book, and a lot of these examples have been greatly simplified. At the time I wrote this, I thought it would be easier to explain starting with creating an iterable with a `[Symbol.iterator]` method and then switching the method out for a generator, but now I think it’s easier just to talk about generators.

**Comment by deanius** [comment]
Thanks for the input - I admire all your tutorials and books, just magic!
