### ISSUE TITLE
OOP, JavaScript, and so-called Classes

### ISSUE THREAD

**Issue by allenwb** [raganwald/raganwald.github.com#45]
This generally looks pretty good.  Ihave just a couple thoughts:

Might be worth mentioning that some languages (but not Snmalltalk, Ruby, JS, CL, etc.) treat class as nominal types.

classes: In Smalltalk and Ruby classes aren't just first class "entities" they are first class objects.

prototypes are not classes:
1) but the "Treaty of Orlando" concluded that they have equivalent power
2) in self, at least, prototypes are frequently used to build class-like program organization structures.  See http://bibliography.selflanguage.org/organizing-programs.html and http://bibliography.selflanguage.org/parents-shared-parts.html .  this has also been found to be common in JS

object-orient programming can mean almost anything: I think it does have a single core meaning (at least to classic OOP programmer): structuring programs in terms of the protocols of sets of communicating entities (objects)

the JavaScript approach:  I'll argue that ES6 classes are as "first class" as the classes of Smalltalk or Ruby. The fisrt class valued of an ES6 class definition is simply a constructor function so an ES^ "class" is nothing more than a first class function object that follows a particular structural pattern that relates it to a prototype object, its "superclass", and its instances.

**Comment by igalic** [comment]
i'm pretty and sure you're not the first people to have extensively thought about this subject.
there's a whole swath of academics who did.
IMO, William Cook has quite well summarized the progress thus far: http://wcook.blogspot.co.at/2012/07/proposal-for-simplified-modern.html

**Comment by allenwb** [comment]
@igalic I don't claim to be the first, but I  *have* been thinking about this stuff for  about 35 years :-)
I even considered linking to Williams work, but was too lazy to track down the links. So thanks.

I'll also probably get flack if I don't recommend: http://wirfs-brock.com/DesignBooks.html if you want to understand what OOP is really about.

**Comment by igalic** [comment]
awesome! thanks for that link!

**Comment by raganwald** [comment]
@allenwb: https://github.com/raganwald/javascript-allonge-six/commit/5273ef7f09f84bdf97c6e01838a837939e43a345?short_path=4ef7780#diff-4ef7780f9adbe102dccda0bb49be9233

**Comment by allenwb** [comment]
regarding Smalltalk and JavaScript:  Here is a talk gave on the topic that drills into the similarities between ES6 classes and Smalltalk classes: https://www.youtube.com/watch?v=EPHmm8JiGbg

**Comment by raganwald** [comment]
> I have been thinking about this stuff for about 35 years

I would claim to have been thinking about this since I discovered Smalltalk in 1986, but the truth is, I've only been playing with these ideas, not researching them.
