### ISSUE TITLE
without 'this' and 'class'

### ISSUE THREAD

**Issue by serapath** [raganwald/raganwald.github.com#48]
> http://raganwald.com/2015/06/04/classes-are-expressions.html

```js
function Person (firstName, lastName) {
  var API; return API = { // could be in two lines, but i use this pattern all the time
    fullName  () {
      return firstName + ' ' + lastName;
    },
    rename    (first, last) {
      firstName = first;
      lastName = last;
      return API;
    }
  };
}
```

**Comment by raganwald** [comment]
Using a closure to simulate private state is a well-known pattern that--like all patterns--has tradeoffs. But it certainly can be used in place of a more traditional prototype-and-property arrangement in some cases.
