### ISSUE TITLE
Lost Symbols

### ISSUE THREAD

**Issue by WebReflection** [raganwald/raganwald.github.com#49]
In [Functional Mixins in ECMAScript 2015](http://raganwald.com/2015/06/17/functional-mixins.html) you go from a simplified approach based on `Object.assign`, and you end up with a more complex approach based on descriptors.

However, `Object.assign` by specifications copies `enumerable` properties values, and also `Symbols`, while your proposed final code ignores Symbols completely.

Either you didn't want to have Symbols usable for mixins, or you forgot to set them too as descriptors.

Accordingly, your final code needs an utility like the following one, if the purpose was to match the original `Object.assign` intent plus enumerability:

```js
function assignWithEnumerability(target, source) {
  return Object
    .getOwnPropertyNames(source)
    .concat(
      Object.getOwnPropertySymbols(source)
    )
    .reduce(
      function (target, key) {
        return Object.defineProperty(
          target,
          key,
          {
            enumerable: Object
              .getOwnPropertyDescriptor(
                source,
                key
              ).enumerable
            ,
            value: source[key]
          }
        );
      },
      target
    )
  ;
}
```

So it can do the meant thing in the right way:
```js
function FunctionalMixin (instanceBehaviour, mixinBehaviour = {}) {
  const typeTag = Symbol("isA");

  function mixin (target) {
    assignWithEnumerability(target, instanceBehaviour);
    target[typeTag] = true;
    return target;
  }
  assignWithEnumerability(mixin, mixinBehaviour);
  mixin[Symbol.instanceOf] = (instance) => !!instance[typeTag];
  return mixin;
}
```

eventually you can make the suggested utility more suitable for your intents having an extra boolean argument that lets the function consider or not enumerability.

**Comment by raganwald** [comment]
I think this is correct from a code point of view, but not from the point of view of gradually adding complexity for the purposes of illustrating the post’s thesis: That there is a tradeoff between using something as simple as the object mixin pattern, or implementing/using something as thorough as https://github.com/WebReflection/es-class.

I’ve tried addressing your (perfectly valid) concern with an afterward: 

https://github.com/raganwald/raganwald.github.com/commit/9e4557703b980a0044a1e12e131dbf8509b31dfd

I’m very interested in your thoughts.

**Comment by WebReflection** [comment]
commented in line. Typo a part, feel free to ignore the rest, since everyone has his/her own opinion about everything ... it's OK

**Comment by raganwald** [comment]
For more information about more extensive mixins:

https://github.com/WebReflection/universal-mixin
